CREATE TABLE [dbo].[FrontUser] (
    [Id]                 UNIQUEIDENTIFIER NOT NULL,
    [PublicId]           INT              IDENTITY (1, 1) NOT NULL,
    [DisplayName]        NVARCHAR (256)   NULL,
    [Username]           NVARCHAR (256)   NULL,
    [Password]           VARCHAR (256)    NOT NULL,
    [FacebookId]         VARCHAR (256)    NULL,
    [TwitterId]          VARCHAR (256)    NULL,
    [GooglePlusId]       VARCHAR (256)    NULL,
    [Photo]              VARCHAR (256)    NULL,
    [Email]              VARCHAR (256)    NULL,
    [CreationDate]       DATETIME         NOT NULL,
    [LastModified]       DATETIME         NULL,
    [LastLogin]          DATETIME         NULL,
    [Status]             INT              CONSTRAINT [DF_FrontUser_Status] DEFAULT ((10)) NOT NULL,
    [Signature]          VARCHAR (512)    NULL,
    [AccessToken]        NVARCHAR (MAX)   NULL,
    [Key]                UNIQUEIDENTIFIER NULL,
    [Salt]               NVARCHAR (MAX)   NULL,
    [VerificationCode]   NVARCHAR (MAX)   NULL,
    [SubscriptionId]     UNIQUEIDENTIFIER NOT NULL,
    [BirthDate]          DATE             NULL,
    [PhoneNumber]        NVARCHAR (20)    NULL,
    [Country]            NVARCHAR (256)   NULL,
    [Gender]             INT              NULL,
    [RefreshToken]       NVARCHAR (MAX)   NULL,
    [RefreshTokenExpiry] DATETIME         NULL,
    [FirstName]          NVARCHAR (256)   NULL,
    [LastName]           NVARCHAR (256)   NULL,
    [SocialProvider]     NVARCHAR (100)   NULL,
    [SocialUserId]       NVARCHAR (100)   NULL,
    [NotificationTopics] NVARCHAR (MAX)   NULL,
    [DeletedByUser]      BIT              NULL,
    CONSTRAINT [PK_FrontUser] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ__FrontUsername] UNIQUE NONCLUSTERED ([Username] ASC, [SubscriptionId] ASC)
);

