CREATE TABLE [dbo].[MediaItem] (
    [Id]             UNIQUEIDENTIFIER NOT NULL,
    [PublicId]       INT              IDENTITY (1, 1) NOT NULL,
    [Caption]        NVARCHAR (256)   NULL,
    [Description]    NVARCHAR (MAX)   NULL,
    [RealHost]       NVARCHAR (50)    NULL,
    [Path]           NVARCHAR (256)   NULL,
    [TempPath]       NVARCHAR (500)   NULL,
    [Extension]      VARCHAR (5)      NULL,
    [Type]           INT              NOT NULL,
    [IsExternal]     BIT              NOT NULL,
    [IsPublic]       BIT              CONSTRAINT [DF_MediaItem_IsPublic] DEFAULT ((1)) NOT NULL,
    [ThumbnailUrl]   NVARCHAR (500)   NULL,
    [CreationDate]   DATETIME         NOT NULL,
    [Version]        INT              NOT NULL,
    [PluginMeta]     NVARCHAR (MAX)   NULL,
    [Source]         INT              CONSTRAINT [DF_MediaItem_Source] DEFAULT ((10)) NOT NULL,
    [CreatedBy]      UNIQUEIDENTIFIER NULL,
    [Duration]       BIGINT           NOT NULL,
    [Tags]           NVARCHAR (MAX)   NULL,
    [Info]           NVARCHAR (MAX)   NULL,
    [Hash]           NVARCHAR (MAX)   NULL,
    [Storage]        NVARCHAR (250)   DEFAULT ('default') NOT NULL,
    [SubscriptionId] UNIQUEIDENTIFIER CONSTRAINT [DF_MediaItem_SubscriptionId] DEFAULT ('67B6364E-D75C-48BF-BC79-A850AC71885A') NOT NULL,
    [Parts]          NVARCHAR (MAX)   NULL,
    [FlixData]       NVARCHAR (MAX)   NULL,
    [ExternalId]     INT              NULL,
    CONSTRAINT [PK_MediaItem] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MediaItem_Subscription] FOREIGN KEY ([SubscriptionId]) REFERENCES [dbo].[Subscription] ([Id]),
    CONSTRAINT [FK_MediaItem_Users] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id])
);

