CREATE TABLE [dbo].[Users] (
    [Id]                 UNIQUEIDENTIFIER NOT NULL,
    [PublicId]           INT              IDENTITY (1, 1) NOT NULL,
    [FirstName]          NVARCHAR (50)    NULL,
    [LastName]           NVARCHAR (50)    NULL,
    [Mobile]             NVARCHAR (20)    NULL,
    [Username]           NVARCHAR (50)    NOT NULL,
    [EmailAddress]       VARCHAR (256)    NOT NULL,
    [PasswordHash]       VARCHAR (256)    NULL,
    [PasswordSalt]       VARCHAR (256)    NULL,
    [LastLogin]          DATETIME         NULL,
    [CreationDate]       DATETIME         CONSTRAINT [DF_Users_CreationDate] DEFAULT (getutcdate()) NOT NULL,
    [Status]             INT              CONSTRAINT [DF_Users_Status] DEFAULT ((10)) NOT NULL,
    [RoleId]             UNIQUEIDENTIFIER NULL,
    [Language]           NVARCHAR (3)     CONSTRAINT [DF_Users_Language] DEFAULT ('ar') NOT NULL,
    [SubscriptionId]     UNIQUEIDENTIFIER CONSTRAINT [DF_Users_SubscriptionId] DEFAULT ('67B6364E-D75C-48BF-BC79-A850AC71885A') NOT NULL,
    [VerificationToken]  NVARCHAR (256)   NULL,
    [AvatarId]           UNIQUEIDENTIFIER NULL,
    [ChatLoginToken]     VARCHAR (256)    NULL,
    [PasswordExpiryDate] DATETIME         NULL,
    [TwoFactorAuthKey]   VARCHAR (256)    NULL,
    [ChatAccount]        BIT              DEFAULT ((0)) NOT NULL,
    [RefreshToken]       NVARCHAR (MAX)   NULL,
    [RefreshTokenExpiry] DATETIME         NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Users_AvatarId] FOREIGN KEY ([AvatarId]) REFERENCES [dbo].[MediaItem] ([Id]),
    CONSTRAINT [FK_Users_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Roles] ([Id]),
    CONSTRAINT [FK_Users_Subscription] FOREIGN KEY ([SubscriptionId]) REFERENCES [dbo].[Subscription] ([Id]),
    CONSTRAINT [PK_Users_Unique_EmailAddress] UNIQUE NONCLUSTERED ([EmailAddress] ASC),
    CONSTRAINT [PK_Users_Unique_Username] UNIQUE NONCLUSTERED ([Username] ASC)
);

