CREATE TABLE [dbo].[UserPackagePurchase] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [UserId]                UNIQUEIDENTIFIER NOT NULL,
    [CreationDate]          DATETIME         NOT NULL,
    [StartDate]             DATETIME         NOT NULL,
    [EndDate]               DATETIME         NOT NULL,
    [Status]                INT              NOT NULL,
    [SubscriptionPackageId] UNIQUEIDENTIFIER NULL,
    [Discount]              FLOAT (53)       NULL,
    [Price]                 FLOAT (53)       NULL,
    [Currency]              NVARCHAR (255)   NULL,
    [Country]               NVARCHAR (255)   NULL,
    [CountryCode]           NVARCHAR (255)   NULL,
    [SubscriptionId]        UNIQUEIDENTIFIER NOT NULL,
    [AndroidPackageId]      NVARCHAR (255)   NULL,
    [IOSPackageId]          NVARCHAR (255)   NULL,
    [Platform]              NVARCHAR (255)   NULL,
    [App]                   NVARCHAR (255)   NULL,
    [OrderId]               NVARCHAR (255)   NULL,
    [RegionCode]            NVARCHAR (255)   NULL,
    [PurchaseState]         NVARCHAR (255)   NULL,
    [PurchaseToken]         NVARCHAR (MAX)   NULL,
    [PurchaseProductId]     NVARCHAR (255)   NULL,
    [PublicId]              INT              IDENTITY (1, 1) NOT NULL,
    [DaysLength]            INT              NULL,
    [ParamsJson]            NVARCHAR (MAX)   NULL,
    [OriginalTransactionId] NVARCHAR (MAX)   NULL,
    [TransactionId]         NVARCHAR (MAX)   NULL,
    [UserAddressId]         UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_UserPackagePurchase] PRIMARY KEY CLUSTERED ([Id] ASC)
);

